import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowRight, Bot, Calendar, Check, CheckCircle2, CreditCard, ExternalLink, FileText, LockKeyhole, Mail, MessageSquareText, Phone, Plus, RefreshCcw, Search, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { useAuth } from '../app/auth';
import { AppLink, navigate } from '../app/router';
import { apiFetch, ApiError } from '../lib/api';
import { supabase } from '../lib/supabase';
import { Card, EmptyState, Field, Money, PrimaryButton, SecondaryButton, SelectField, Spinner, StatusPill, TextareaField } from '../components/saas/ui';

function useData<T>(path: string, initial: T) {
  const { workspaceId } = useAuth();
  const [data,setData]=useState<T>(initial); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const refresh=async()=>{if(!workspaceId)return;setLoading(true);setError('');try{setData(await apiFetch<T>(path,{},workspaceId))}catch(err:any){setError(err.message)}finally{setLoading(false)}};
  useEffect(()=>{void refresh()},[workspaceId,path]);
  return {data,loading,error,refresh};
}

export function DashboardPage() {
  const query=useData<any>('/api/dashboard',{metrics:{},today:[]});
  if(query.loading)return <Spinner label="Loading revenue dashboard…"/>;
  if(query.error)return <ErrorBox message={query.error} onRetry={query.refresh}/>;
  const m=query.data.metrics;
  const cards=[['Month revenue',<Money cents={m.monthRevenueCents||0}/>,'Money received this month'],['Outstanding',<Money cents={m.outstandingCents||0}/>,'Open invoice balances'],['New leads',String(m.newLeads||0),'Needs attention'],['AI actions',String(m.aiActions||0),'This month']];
  return <Page title="Home" eyebrow="Revenue overview" action={<SecondaryButton onClick={()=>query.refresh()}><RefreshCcw className="mr-2 inline h-4 w-4"/>Refresh</SecondaryButton>}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,sub])=><Card key={String(label)} className="p-5"><p className="text-xs font-semibold text-slate-500">{label}</p><div className="mt-2 text-3xl font-black tracking-tight">{value}</div><p className="mt-1 text-xs text-slate-400">{sub}</p></Card>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><Card className="p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">Today's work</h2><p className="text-xs text-slate-500">Scheduled jobs in this workspace</p></div><AppLink href="/app/schedule" className="text-xs font-semibold text-indigo-600">Open schedule</AppLink></div>{query.data.today?.length?<div className="space-y-2">{query.data.today.map((job:any)=><div key={job.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100"><Calendar className="h-4 w-4"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{job.title}</p><p className="text-xs text-slate-500">{job.customers?.display_name||'Customer'} · {job.scheduled_start?new Date(job.scheduled_start).toLocaleTimeString('en-AU',{hour:'numeric',minute:'2-digit'}):'Time pending'}</p></div><StatusPill>{job.status}</StatusPill></div>)}</div>:<EmptyState title="Nothing scheduled today" description="Bookings and jobs will appear here as the booking engine creates work."/>}</Card><Card className="p-5"><h2 className="font-bold">What Jobryn should surface</h2><div className="mt-4 space-y-3">{[[m.openQuotes,'Open quotes','/app/quotes'],[m.newLeads,'New leads','/app/leads'],[m.bookedLeads,'Booked / won leads','/app/leads']].map(([count,label,href])=><AppLink href={String(href)} key={String(label)} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-sm"><span>{label}</span><span className="font-black">{count||0}</span></AppLink>)}</div></Card></div></Page>;
}

export function CommandCentrePage() {
  const {workspaceId}=useAuth(); const [command,setCommand]=useState(''); const [result,setResult]=useState<any>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const run=async(text=command)=>{if(!workspaceId||!text.trim())return;setBusy(true);setError('');try{setResult(await apiFetch('/api/operator/command',{method:'POST',body:JSON.stringify({command:text})},workspaceId))}catch(err:any){setError(err.message)}finally{setBusy(false)}};
  return <Page title="Command Centre" eyebrow="Controlled Operator"><Card className="overflow-hidden"><div className="border-b border-slate-100 bg-slate-950 p-6 text-white"><div className="mb-3 flex items-center gap-2 text-sm font-semibold text-indigo-300"><Sparkles className="h-4 w-4"/>Ask Jobryn about your business</div><form className="flex gap-2" onSubmit={e=>{e.preventDefault();void run()}}><input value={command} onChange={e=>setCommand(e.target.value)} placeholder="Who owes us money?" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-sm text-white outline-none placeholder:text-slate-500 focus:border-indigo-400"/><button disabled={busy} className="rounded-xl bg-indigo-500 px-5 text-sm font-semibold text-white disabled:opacity-50">{busy?'Working…':'Run'}</button></form><div className="mt-3 flex flex-wrap gap-2">{["What's happening today?","Who owes us money?","Which lead source made the most money?","Follow up quotes older than three days."].map(s=><button key={s} onClick={()=>{setCommand(s);void run(s)}} className="rounded-full bg-white/10 px-3 py-1.5 text-xs text-slate-300 hover:bg-white/15">{s}</button>)}</div></div><div className="p-6">{error&&<p className="text-sm text-red-600">{error}</p>}{!result&&!error&&<p className="text-sm text-slate-500">This hardened first version executes supported read-only commands and prepares approval-gated write proposals. It does not let the model bypass permissions.</p>}{result&&<CommandResult result={result}/>}</div></Card></Page>;
}

function CommandResult({result}:{result:any}) { return <div><div className="flex items-center justify-between"><div><h3 className="text-lg font-bold">{result.title}</h3><p className="mt-1 text-sm text-slate-500">{result.summary}</p></div>{result.approvalRequired&&<StatusPill tone="amber">Approval required</StatusPill>}</div>{typeof result.totalCents==='number'&&<div className="mt-5 text-4xl font-black"><Money cents={result.totalCents}/></div>}{result.rows?.length>0&&<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><tbody>{result.rows.slice(0,20).map((row:any,i:number)=><tr key={row.id||row.source||i} className="border-t border-slate-100"><td className="py-3 font-semibold">{row.customers?.display_name||row.source||row.title||`#${row.invoice_number||row.quote_number||row.job_number||''}`}</td><td className="py-3 text-slate-500">{row.status||''}</td><td className="py-3 text-right font-semibold">{row.balance_due_cents!=null?<Money cents={row.balance_due_cents}/>:row.revenue_cents!=null?<Money cents={row.revenue_cents}/>:''}</td></tr>)}</tbody></table></div>}</div> }

export function CustomersPage() {
  const {workspaceId}=useAuth(); const query=useData<any>('/api/crm/customers',{customers:[]}); const [open,setOpen]=useState(false);const [form,setForm]=useState({first_name:'',last_name:'',phone:'',email:'',source:'website',notes:''});const [error,setError]=useState('');
  const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!workspaceId)return;const next=(e.nativeEvent as SubmitEvent).submitter instanceof HTMLButtonElement&&(e.nativeEvent as SubmitEvent).submitter?.getAttribute('data-next')==='job';setError('');try{const result=await apiFetch<any>('/api/crm/customers',{method:'POST',body:JSON.stringify({...form,email:form.email||null,phone:form.phone||null})},workspaceId);setForm({first_name:'',last_name:'',phone:'',email:'',source:'website',notes:''});setOpen(false);await query.refresh();if(next&&result.customer?.id)navigate(`/app/jobs?customer=${encodeURIComponent(result.customer.id)}`)}catch(err:any){setError(err.message)}};
  return <Page title="Customers" eyebrow="Customer memory" action={<PrimaryButton onClick={()=>setOpen(!open)}><Plus className="mr-2 inline h-4 w-4"/>New customer</PrimaryButton>}>{open&&<Card className="mb-5 p-5"><form onSubmit={create} className="grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><h2 className="font-bold">Add the customer first</h2><p className="mt-1 text-sm text-slate-500">Save their details, then continue directly into the job workflow.</p></div><Field label="First name" value={form.first_name} onChange={e=>setForm(v=>({...v,first_name:e.target.value}))}/><Field label="Last name" value={form.last_name} onChange={e=>setForm(v=>({...v,last_name:e.target.value}))}/><Field label="Phone" value={form.phone} onChange={e=>setForm(v=>({...v,phone:e.target.value}))}/><Field label="Email" type="email" value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))}/><SelectField label="Source" value={form.source} onChange={e=>setForm(v=>({...v,source:e.target.value}))}><option>website</option><option>google</option><option>facebook</option><option>missed_call</option><option>referral</option><option>existing_customer</option></SelectField><div className="sm:col-span-2"><TextareaField label="Notes" value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))}/></div>{error&&<p className="text-sm text-red-600 sm:col-span-2">{error}</p>}<div className="flex flex-wrap gap-2 sm:col-span-2"><PrimaryButton data-next="job">Save customer & create job <ArrowRight className="ml-1 inline h-4 w-4"/></PrimaryButton><SecondaryButton>Save customer only</SecondaryButton></div></form></Card>}{query.loading?<Spinner/>:query.error?<ErrorBox message={query.error} onRetry={query.refresh}/>:query.data.customers.length?<Card className="overflow-hidden"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Contact</th><th className="px-4 py-3">Source</th><th className="px-4 py-3 text-right">Lifetime value</th></tr></thead><tbody>{query.data.customers.map((c:any)=><tr key={c.id} className="border-t border-slate-100"><td className="px-4 py-3 font-semibold">{c.display_name}</td><td className="px-4 py-3 text-slate-500"><div>{c.phone||'—'}</div><div>{c.email||''}</div></td><td className="px-4 py-3"><StatusPill>{c.source||'unknown'}</StatusPill></td><td className="px-4 py-3 text-right font-semibold"><Money cents={c.lifetime_value_cents||0}/></td></tr>)}</tbody></table></Card>:<EmptyState title="No customers yet" description="Create a customer manually or let Jobryn create one from a real enquiry."/>}</Page>;
}

const stages=['new','contacted','qualified','quote','booked','won','completed'];
export function LeadsPage() {
  const query=useData<any>('/api/crm/leads',{leads:[]});
  if(query.loading)return <Page title="Leads" eyebrow="Revenue pipeline"><Spinner/></Page>;
  return <Page title="Leads" eyebrow="Revenue pipeline" action={<SecondaryButton onClick={()=>query.refresh()}>Refresh</SecondaryButton>}>{query.error?<ErrorBox message={query.error}/>:<div className="grid auto-cols-[280px] grid-flow-col gap-4 overflow-x-auto pb-4">{stages.map(stage=><div key={stage}><div className="mb-2 flex items-center justify-between"><h3 className="text-xs font-bold uppercase tracking-wider text-slate-500">{stage}</h3><span className="text-xs text-slate-400">{query.data.leads.filter((l:any)=>l.stage===stage).length}</span></div><div className="space-y-3">{query.data.leads.filter((l:any)=>l.stage===stage).map((lead:any)=><Card key={lead.id} className="p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-bold">{lead.title}</p><p className="mt-1 text-xs text-slate-500">{lead.customers?.display_name||'Unmatched customer'}</p></div>{lead.estimated_value_cents!=null&&<span className="text-xs font-bold"><Money cents={lead.estimated_value_cents}/></span>}</div><div className="mt-3 flex items-center justify-between text-[11px] text-slate-400"><span>{lead.source||'unknown source'}</span><span>{new Date(lead.created_at).toLocaleDateString('en-AU')}</span></div></Card>)}{!query.data.leads.some((l:any)=>l.stage===stage)&&<div className="rounded-xl border border-dashed border-slate-200 p-4 text-center text-xs text-slate-400">No leads</div>}</div></div>)}</div>}</Page>;
}

export function InboxPage() {
  const query=useData<any>('/api/intelligence/conversations',{conversations:[]});
  return <Page title="Inbox" eyebrow="Unified communications">{query.loading?<Spinner/>:query.error?<ErrorBox message={query.error}/>:query.data.conversations.length?<div className="grid gap-4 lg:grid-cols-[360px_1fr]"><Card className="overflow-hidden">{query.data.conversations.map((c:any)=><div key={c.id} className="border-b border-slate-100 p-4 last:border-0"><div className="flex items-center justify-between"><p className="font-semibold">{c.customers?.display_name||'Unknown contact'}</p><StatusPill tone={c.handling_mode==='ai_active'?'indigo':'amber'}>{c.handling_mode}</StatusPill></div><p className="mt-1 truncate text-xs text-slate-500">{c.subject||c.customers?.phone||c.customers?.email||'Conversation'}</p></div>)}</Card><EmptyState title="Select a conversation" description="Conversation detail and human handoff controls use the same canonical customer/conversation model."/></div>:<EmptyState title="No conversations yet" description="SMS, email, web chat and phone conversations will appear here once their providers are connected."/>}</Page>;
}

export function OperationsListPage({kind}:{kind:'appointments'|'jobs'|'quotes'|'invoices'|'payments'}) {
  if(kind==='jobs')return <JobsWorkflowPage/>;
  if(kind==='quotes'||kind==='invoices')return <FinancialDocumentsPage kind={kind}/>;
  const names={appointments:['Schedule','Bookings and availability'],jobs:['Jobs','Operational work'],quotes:['Quotes','Sales'],invoices:['Invoices','Money owed'],payments:['Payments','Money received']} as const;
  const query=useData<any>(`/api/operations/${kind}`,{[kind]:[]});
  const rows=query.data[kind]||[];
  return <Page title={names[kind][0]} eyebrow={names[kind][1]}>{query.loading?<Spinner/>:query.error?<ErrorBox message={query.error}/>:rows.length?<Card className="overflow-hidden"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">Record</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Value / Time</th></tr></thead><tbody>{rows.map((row:any)=><tr key={row.id} className="border-t border-slate-100"><td className="px-4 py-3 font-semibold">{row.title||`#${row.job_number||row.quote_number||row.invoice_number||row.id.slice(0,8)}`}</td><td className="px-4 py-3 text-slate-500">{row.customers?.display_name||'—'}</td><td className="px-4 py-3"><StatusPill tone={['paid','succeeded','completed','accepted','confirmed'].includes(row.status)?'green':['overdue','failed','cancelled'].includes(row.status)?'red':'slate'}>{row.status}</StatusPill></td><td className="px-4 py-3 text-right font-semibold">{row.amount_cents!=null?<Money cents={row.amount_cents}/>:row.balance_due_cents!=null?<Money cents={row.balance_due_cents}/>:row.total_cents!=null?<Money cents={row.total_cents}/>:row.starts_at?new Date(row.starts_at).toLocaleString('en-AU',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}):row.scheduled_start?new Date(row.scheduled_start).toLocaleString('en-AU',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}):'—'}</td></tr>)}</tbody></table></Card>:<EmptyState title={`No ${kind} yet`} description={`The ${names[kind][0].toLowerCase()} database and secure API are live. Records appear here when the workflow creates them.`}/>}</Page>;
}

function FinancialDocumentsPage({kind}:{kind:'quotes'|'invoices'}) {
  const {workspaceId}=useAuth();
  const records=useData<any>(`/api/operations/${kind}`,{[kind]:[]});
  const customers=useData<any>('/api/crm/customers',{customers:[]});
  const jobs=useData<any>('/api/operations/jobs',{jobs:[]});
  const singular=kind==='quotes'?'quote':'invoice';
  const title=kind==='quotes'?'Quotes':'Invoices';
  const [open,setOpen]=useState(false);const [step,setStep]=useState(0);const [busy,setBusy]=useState<boolean|string>(false);const [error,setError]=useState('');const [created,setCreated]=useState<any>(null);const [paymentLink,setPaymentLink]=useState('');
  const [form,setForm]=useState({customer_id:'',job_id:'',date:'',notes:'',terms:'',deposit_dollars:'',items:[{description:'',quantity:1,unit_price_dollars:'',gst:true}]});
  const availableJobs=jobs.data.jobs.filter((j:any)=>!form.customer_id||j.customer_id===form.customer_id);
  const totals=form.items.reduce((t,item)=>{const subtotal=Math.round(Number(item.quantity||0)*Number(item.unit_price_dollars||0)*100);return {subtotal:t.subtotal+subtotal,gst:t.gst+(item.gst?Math.round(subtotal*.1):0)}},{subtotal:0,gst:0});
  const reset=()=>{setForm({customer_id:'',job_id:'',date:'',notes:'',terms:'',deposit_dollars:'',items:[{description:'',quantity:1,unit_price_dollars:'',gst:true}]});setStep(0);setError('');setCreated(null);setOpen(true)};
  const next=(e:React.FormEvent)=>{e.preventDefault();setError('');if(step===0&&!form.customer_id)return setError('Choose a customer before continuing.');if(step===1&&form.items.some(i=>!i.description.trim()||Number(i.quantity)<=0||Number(i.unit_price_dollars)<0))return setError('Complete every line item before continuing.');setStep(v=>Math.min(v+1,2))};
  const updateItem=(index:number,patch:any)=>setForm(v=>({...v,items:v.items.map((item,i)=>i===index?{...item,...patch}:item)}));
  const create=async()=>{if(!workspaceId)return;setBusy(true);setError('');try{const body:any={customer_id:form.customer_id,job_id:form.job_id||null,items:form.items.map(i=>({description:i.description.trim(),quantity:Number(i.quantity),unit_price_cents:Math.round(Number(i.unit_price_dollars)*100),gst_rate:i.gst ? 0.1 : 0}))};if(kind==='quotes'){body.expires_at=form.date?new Date(`${form.date}T23:59:59`).toISOString():null;body.terms=form.terms;body.notes=form.notes;body.deposit_cents=Math.round(Number(form.deposit_dollars||0)*100)}else body.due_at=form.date?new Date(`${form.date}T23:59:59`).toISOString():null;const result=await apiFetch<any>(`/api/operations/${kind}`,{method:'POST',body:JSON.stringify(body)},workspaceId);setCreated(result[singular]);await records.refresh()}catch(err:any){setError(err.message)}finally{setBusy(false)}};
  const createPaymentLink=async(invoiceId:string)=>{if(!workspaceId)return;setBusy(invoiceId);setError('');setPaymentLink('');try{const result=await apiFetch<any>(`/api/operations/invoices/${invoiceId}/checkout`,{method:'POST',headers:{'idempotency-key':crypto.randomUUID()}},workspaceId);setPaymentLink(result.checkoutUrl);try{await navigator.clipboard.writeText(result.checkoutUrl)}catch{/* The visible field remains available when clipboard access is denied. */}}catch(err:any){setError(err.message)}finally{setBusy(false)}};
  const rows=records.data[kind]||[];
  return <Page title={title} eyebrow={kind==='quotes'?'Price work clearly':'Money owed'} action={<PrimaryButton onClick={reset}><Plus className="mr-2 inline h-4 w-4"/>New {singular}</PrimaryButton>}>
    {open&&<Card className="mb-6 overflow-hidden"><div className="grid grid-cols-3 gap-2 border-b border-slate-100 bg-slate-50 p-5">{['Customer & job','Line items','Review'].map((label,index)=><div key={label}><div className={`h-1.5 rounded-full ${index<=step?'bg-indigo-600':'bg-slate-200'}`}/><p className={`mt-2 text-xs font-semibold ${index===step?'text-indigo-700':'text-slate-500'}`}>{index+1}. {label}</p></div>)}</div><div className="p-6">{created?<div className="py-3 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><Check className="h-7 w-7"/></div><h2 className="mt-4 text-2xl font-black">Draft {singular} created</h2><p className="mt-2 text-sm text-slate-500">It is saved securely as a draft. Sending will remain disabled until email delivery and public document security are connected.</p><div className="mt-6 flex justify-center gap-2"><PrimaryButton onClick={()=>setOpen(false)}>View {kind}</PrimaryButton><SecondaryButton onClick={reset}>Create another</SecondaryButton></div></div>:<form onSubmit={next}>
      {step===0&&<div><h2 className="text-xl font-bold">Connect this {singular}</h2><p className="mt-1 text-sm text-slate-500">Choose the customer and, where relevant, the job it belongs to.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><SelectField label="Customer" value={form.customer_id} onChange={e=>setForm(v=>({...v,customer_id:e.target.value,job_id:''}))} required><option value="">Choose a customer…</option>{customers.data.customers.map((c:any)=><option key={c.id} value={c.id}>{c.display_name}</option>)}</SelectField><SelectField label="Related job (optional)" value={form.job_id} onChange={e=>setForm(v=>({...v,job_id:e.target.value}))}><option value="">No related job</option>{availableJobs.map((j:any)=><option key={j.id} value={j.id}>{j.title}</option>)}</SelectField><Field label={kind==='quotes'?'Expiry date (optional)':'Due date (optional)'} type="date" value={form.date} onChange={e=>setForm(v=>({...v,date:e.target.value}))}/></div></div>}
      {step===1&&<div><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold">What are you charging for?</h2><p className="mt-1 text-sm text-slate-500">Jobryn calculates totals and GST on the server.</p></div><SecondaryButton type="button" onClick={()=>setForm(v=>({...v,items:[...v.items,{description:'',quantity:1,unit_price_dollars:'',gst:true}]}))}>Add line</SecondaryButton></div><div className="mt-5 space-y-3">{form.items.map((item,index)=><div key={index} className="grid gap-3 rounded-xl border border-slate-200 p-4 sm:grid-cols-[1fr_100px_140px_auto]"><Field label="Description" value={item.description} onChange={e=>updateItem(index,{description:e.target.value})} required/><Field label="Quantity" type="number" min="0.001" step="0.001" value={item.quantity} onChange={e=>updateItem(index,{quantity:Number(e.target.value)})} required/><Field label="Unit price (AUD)" type="number" min="0" step="0.01" value={item.unit_price_dollars} onChange={e=>updateItem(index,{unit_price_dollars:e.target.value})} required/><div className="flex items-end gap-2 pb-2"><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={item.gst} onChange={e=>updateItem(index,{gst:e.target.checked})}/>GST</label>{form.items.length>1&&<button type="button" onClick={()=>setForm(v=>({...v,items:v.items.filter((_,i)=>i!==index)}))} className="text-xs font-bold text-red-600">Remove</button>}</div></div>)}</div>{kind==='quotes'&&<div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Deposit requested (AUD)" type="number" min="0" step="0.01" value={form.deposit_dollars} onChange={e=>setForm(v=>({...v,deposit_dollars:e.target.value}))}/><TextareaField label="Terms" value={form.terms} onChange={e=>setForm(v=>({...v,terms:e.target.value}))}/><div className="sm:col-span-2"><TextareaField label="Internal notes" value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))}/></div></div>}</div>}
      {step===2&&<div><h2 className="text-xl font-bold">Review the draft</h2><p className="mt-1 text-sm text-slate-500">Nothing will be sent to the customer yet.</p><div className="mt-5 rounded-xl border border-slate-200 p-5"><div className="space-y-3">{form.items.map((item,index)=><div key={index} className="flex justify-between gap-4 text-sm"><span>{item.description} × {item.quantity}</span><span className="font-semibold"><Money cents={Math.round(Number(item.quantity)*Number(item.unit_price_dollars)*100)}/></span></div>)}</div><div className="mt-4 space-y-2 border-t border-slate-200 pt-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><Money cents={totals.subtotal}/></div><div className="flex justify-between"><span>GST</span><Money cents={totals.gst}/></div><div className="flex justify-between text-lg font-black"><span>Total</span><Money cents={totals.subtotal+totals.gst}/></div></div></div></div>}
      {error&&<p className="mt-4 text-sm font-medium text-red-600">{error}</p>}<div className="mt-6 flex justify-between gap-2">{step>0?<SecondaryButton type="button" onClick={()=>{setError('');setStep(v=>v-1)}}>Back</SecondaryButton>:<span/>}{step<2?<PrimaryButton>Save & continue <ArrowRight className="ml-1 inline h-4 w-4"/></PrimaryButton>:<PrimaryButton type="button" disabled={Boolean(busy)} onClick={create}>{busy?'Creating…':`Create draft ${singular}`}</PrimaryButton>}</div>
    </form>}</div></Card>}
    {error&&!open&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{paymentLink&&<Card className="mb-4 p-4"><p className="text-sm font-bold text-emerald-700">Secure Stripe payment link created and copied</p><p className="mt-1 text-xs text-slate-500">Card and bank details are entered only on Stripe. Share this link with the intended customer.</p><input readOnly value={paymentLink} onFocus={e=>e.currentTarget.select()} className="mt-3 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs"/></Card>}
    {records.loading?<Spinner/>:records.error?<ErrorBox message={records.error} onRetry={records.refresh}/>:rows.length?<Card className="overflow-hidden"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">Record</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Total</th>{kind==='invoices'&&<th className="px-4 py-3 text-right">Payment</th>}</tr></thead><tbody>{rows.map((row:any)=><tr key={row.id} className="border-t border-slate-100"><td className="px-4 py-3 font-semibold">#{row.quote_number||row.invoice_number}</td><td className="px-4 py-3 text-slate-500">{row.customers?.display_name||'—'}</td><td className="px-4 py-3"><StatusPill>{row.status}</StatusPill></td><td className="px-4 py-3 text-right font-semibold"><Money cents={row.total_cents||0}/></td>{kind==='invoices'&&<td className="px-4 py-3 text-right">{Number(row.balance_due_cents)>0&&!['void','refunded'].includes(row.status)?<SecondaryButton disabled={busy===row.id} onClick={()=>createPaymentLink(row.id)}>{busy===row.id?'Creating…':'Secure payment link'}</SecondaryButton>:<span className="text-xs text-slate-400">Settled</span>}</td>}</tr>)}</tbody></table></Card>:<EmptyState title={`No ${kind} yet`} description={`Create the first ${singular} with the guided workflow.`}/>}
  </Page>;
}

function JobsWorkflowPage() {
  const {workspaceId}=useAuth();
  const jobs=useData<any>('/api/operations/jobs',{jobs:[]});
  const customers=useData<any>('/api/crm/customers',{customers:[]});
  const initialCustomer=new URLSearchParams(window.location.search).get('customer')||'';
  const [open,setOpen]=useState(Boolean(initialCustomer));
  const [step,setStep]=useState(0);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const [created,setCreated]=useState<any>(null);
  const [form,setForm]=useState({customer_id:initialCustomer,title:'',description:'',address_text:'',scheduled_start:'',scheduled_end:''});
  const steps=['Customer','Job details','Schedule','Review'];
  const selectedCustomer=customers.data.customers.find((c:any)=>c.id===form.customer_id);
  const reset=()=>{setForm({customer_id:'',title:'',description:'',address_text:'',scheduled_start:'',scheduled_end:''});setStep(0);setCreated(null);setError('');setOpen(true)};
  const continueStep=(e:React.FormEvent)=>{e.preventDefault();setError('');if(step===0&&!form.customer_id)return setError('Choose a customer before continuing.');if(step===1&&!form.title.trim())return setError('Add a short job title before continuing.');if(step===2&&Boolean(form.scheduled_start)!==Boolean(form.scheduled_end))return setError('Add both a start and finish time, or leave both blank to schedule later.');setStep(v=>Math.min(v+1,3))};
  const create=async()=>{if(!workspaceId)return;setBusy(true);setError('');try{const result=await apiFetch<any>('/api/operations/jobs',{method:'POST',body:JSON.stringify({customer_id:form.customer_id,title:form.title.trim(),description:form.description.trim(),address_text:form.address_text.trim()||null,scheduled_start:form.scheduled_start?new Date(form.scheduled_start).toISOString():null,scheduled_end:form.scheduled_end?new Date(form.scheduled_end).toISOString():null})},workspaceId);setCreated(result.job);await jobs.refresh()}catch(err:any){setError(err.message)}finally{setBusy(false)}};
  const setStart=(value:string)=>{setForm(v=>{const start=value?new Date(value):null;const end=start?new Date(start.getTime()+60*60*1000):null;return {...v,scheduled_start:value,scheduled_end:end?`${end.getFullYear()}-${String(end.getMonth()+1).padStart(2,'0')}-${String(end.getDate()).padStart(2,'0')}T${String(end.getHours()).padStart(2,'0')}:${String(end.getMinutes()).padStart(2,'0')}`:''}})};
  return <Page title="Jobs" eyebrow="Guided job workflow" action={<PrimaryButton onClick={reset}><Plus className="mr-2 inline h-4 w-4"/>New job</PrimaryButton>}>
    {open&&<Card className="mb-6 overflow-hidden"><div className="border-b border-slate-100 bg-slate-50 p-5"><div className="grid grid-cols-4 gap-2">{steps.map((label,index)=><div key={label}><div className={`h-1.5 rounded-full ${index<=step?'bg-indigo-600':'bg-slate-200'}`}/><p className={`mt-2 text-xs font-semibold ${index===step?'text-indigo-700':'text-slate-500'}`}>{index+1}. {label}</p></div>)}</div></div>
      <div className="p-6">{created?<div className="py-3 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><Check className="h-7 w-7"/></div><h2 className="mt-4 text-2xl font-black">Job created</h2><p className="mt-2 text-sm text-slate-500">{created.title} is saved securely. Choose what you want to do next.</p><div className="mt-6 flex flex-wrap justify-center gap-2"><PrimaryButton onClick={()=>{setOpen(false);setCreated(null)}}>View jobs</PrimaryButton><SecondaryButton onClick={reset}>Create another job</SecondaryButton><SecondaryButton onClick={()=>navigate('/app/schedule')}>Open schedule</SecondaryButton></div></div>:<form onSubmit={continueStep}>
        {step===0&&<div><h2 className="text-xl font-bold">Who is this job for?</h2><p className="mt-1 text-sm text-slate-500">Select the customer so every later quote, invoice and payment can stay connected.</p><div className="mt-5"><SelectField label="Customer" value={form.customer_id} onChange={e=>setForm(v=>({...v,customer_id:e.target.value}))} required><option value="">Choose a customer…</option>{customers.data.customers.map((c:any)=><option key={c.id} value={c.id}>{c.display_name}</option>)}</SelectField></div>{!customers.loading&&!customers.data.customers.length&&<div className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-800">Add a customer before creating a job. <AppLink href="/app/customers" className="font-bold underline">Create customer</AppLink></div>}</div>}
        {step===1&&<div><h2 className="text-xl font-bold">What work needs doing?</h2><p className="mt-1 text-sm text-slate-500">Give the team enough context to understand the outcome and location.</p><div className="mt-5 grid gap-4"><Field label="Job title" value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))} required placeholder="Repair leaking kitchen tap"/><TextareaField label="Description" value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))} placeholder="Scope, access notes, parts or customer expectations"/><Field label="Job address" value={form.address_text} onChange={e=>setForm(v=>({...v,address_text:e.target.value}))} placeholder="Street, suburb and postcode"/></div></div>}
        {step===2&&<div><h2 className="text-xl font-bold">When should it happen?</h2><p className="mt-1 text-sm text-slate-500">Add the booking now, or leave both fields blank and schedule it later.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Start" type="datetime-local" value={form.scheduled_start} onChange={e=>setStart(e.target.value)}/><Field label="Finish" type="datetime-local" value={form.scheduled_end} onChange={e=>setForm(v=>({...v,scheduled_end:e.target.value}))}/></div></div>}
        {step===3&&<div><h2 className="text-xl font-bold">Review and create</h2><p className="mt-1 text-sm text-slate-500">Confirm the details before Jobryn creates the operational record.</p><div className="mt-5 divide-y divide-slate-100 rounded-xl border border-slate-200">{[['Customer',selectedCustomer?.display_name||'—'],['Job',form.title],['Address',form.address_text||'Not added'],['Schedule',form.scheduled_start?`${new Date(form.scheduled_start).toLocaleString('en-AU')} → ${new Date(form.scheduled_end).toLocaleString('en-AU')}`:'Schedule later']].map(([label,value])=><div key={label} className="flex gap-4 p-4 text-sm"><span className="w-24 flex-none font-semibold text-slate-500">{label}</span><span className="font-medium text-slate-900">{value}</span></div>)}</div></div>}
        {error&&<p className="mt-4 text-sm font-medium text-red-600">{error}</p>}<div className="mt-6 flex flex-wrap justify-between gap-2">{step>0?<SecondaryButton type="button" onClick={()=>{setError('');setStep(v=>v-1)}}>Back</SecondaryButton>:<span/>}{step<3?<PrimaryButton disabled={customers.loading}>{step===0?'Save & continue to job details':step===1?'Save & continue to schedule':'Save & continue to review'} <ArrowRight className="ml-1 inline h-4 w-4"/></PrimaryButton>:<PrimaryButton type="button" disabled={busy} onClick={create}>{busy?'Creating job…':'Create job & complete'}</PrimaryButton>}</div>
      </form>}</div></Card>}
    {jobs.loading?<Spinner/>:jobs.error?<ErrorBox message={jobs.error} onRetry={jobs.refresh}/>:jobs.data.jobs.length?<Card className="overflow-hidden"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">Job</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Scheduled</th></tr></thead><tbody>{jobs.data.jobs.map((job:any)=><tr key={job.id} className="border-t border-slate-100"><td className="px-4 py-3 font-semibold">{job.title}</td><td className="px-4 py-3 text-slate-500">{job.customers?.display_name||'—'}</td><td className="px-4 py-3"><StatusPill tone={job.status==='completed'?'green':'slate'}>{job.status}</StatusPill></td><td className="px-4 py-3 text-right text-slate-600">{job.scheduled_start?new Date(job.scheduled_start).toLocaleString('en-AU',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}):'Not scheduled'}</td></tr>)}</tbody></table></Card>:<EmptyState title="No jobs yet" description="Create the first job with the guided workflow. Jobryn will keep the customer, work, schedule and later revenue records connected."/>}
  </Page>;
}

export function BillingPage() {
  const {workspaceId}=useAuth();const query=useData<any>('/api/billing/status',{subscription:null,entitlements:[],stripeConfigured:false});const [busy,setBusy]=useState('');const [error,setError]=useState('');
  const checkout=async(plan:string)=>{if(!workspaceId)return;setBusy(plan);setError('');try{const result=await apiFetch<any>('/api/billing/checkout',{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify({plan})},workspaceId);window.location.assign(result.checkoutUrl)}catch(err:any){if(err instanceof ApiError&&err.code==='ACTIVE_SUBSCRIPTION_EXISTS')return portal();setError(err.message);setBusy('')}};
  const portal=async()=>{if(!workspaceId)return;setBusy('portal');setError('');try{const result=await apiFetch<any>('/api/billing/portal',{method:'POST'},workspaceId);window.location.assign(result.portalUrl)}catch(err:any){setError(err.message);setBusy('')}};
  const plans=[['starter','Starter',149,'Core CRM, leads, booking and basic AI'],['growth','Growth',299,'Advanced automation and revenue campaigns'],['operator','Operator',599,'Full Operator entitlement and higher limits']];
  return <Page title="Billing" eyebrow="Stripe subscriptions" action={query.data.subscription?.stripe_customer_id?<SecondaryButton disabled={!!busy} onClick={portal}><ExternalLink className="mr-2 inline h-4 w-4"/>Manage in Stripe</SecondaryButton>:undefined}>{query.loading?<Spinner/>:<><Card className="mb-6 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold text-slate-500">Current plan</p><h2 className="mt-1 text-2xl font-black capitalize">{query.data.subscription?.plan||'starter'}</h2><p className="mt-1 text-sm text-slate-500">Status: {query.data.subscription?.status||'not active'}{query.data.subscription?.status==='trialing'&&query.data.subscription?.trial_ends_at?` · trial ends ${new Date(query.data.subscription.trial_ends_at).toLocaleDateString('en-AU')}`:''}{query.data.subscription?.status==='past_due'&&query.data.subscription?.grace_period_ends_at?` · grace until ${new Date(query.data.subscription.grace_period_ends_at).toLocaleDateString('en-AU')}`:''}</p></div><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-emerald-600"/><span className="text-sm font-semibold">Stripe-hosted secure billing</span></div></div></Card>{error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}{/MFA_REQUIRED/i.test(error)&&<button onClick={()=>navigate('/app/settings/security')} className="ml-2 font-bold underline">Set up MFA</button>}</div>}<div className="grid gap-4 lg:grid-cols-3">{plans.map(([key,name,price,desc])=><Card key={String(key)} className="p-6"><h3 className="text-lg font-bold">{name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-slate-500">{desc}</p><div className="mt-5"><span className="text-4xl font-black">${price}</span><span className="text-sm text-slate-500"> / month AUD</span></div><PrimaryButton disabled={!query.data.stripeConfigured||!!busy} onClick={()=>checkout(String(key))} className="mt-5 w-full">{busy===key?'Opening Stripe…':query.data.subscription?.plan===key?'Current plan':`Choose ${name}`}</PrimaryButton></Card>)}</div>{!query.data.stripeConfigured&&<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Stripe server keys and Price IDs are not configured in this environment yet. Checkout stays disabled instead of simulating payment success.</div>}</>}</Page>;
}

export function IntegrationsPage() {
  const query=useData<any>('/api/integrations',{integrations:[]}); const by=new Map((query.data.integrations||[]).map((i:any)=>[i.provider,i]));
  const providers=[['google_calendar','Google Calendar','Booking conflict and event sync'],['stripe','Stripe','Subscriptions and customer payments'],['twilio','Twilio','SMS and phone'],['email','Email provider','Transactional and marketing email'],['xero','Xero','Accounting sync'],['meta','Meta','Facebook and Instagram']];
  return <Page title="Integrations" eyebrow="Provider health"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{providers.map(([key,name,desc])=>{const item:any=by.get(key);return <Card key={key} className="p-5"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 font-black">{name[0]}</div><StatusPill tone={item?.status==='connected'?'green':item?.status==='failed'?'red':'slate'}>{item?.status||'not connected'}</StatusPill></div><h3 className="mt-4 font-bold">{name}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{desc}</p><SecondaryButton disabled className="mt-4 w-full">{item?.status==='connected'?'Manage':'Connect when provider OAuth is configured'}</SecondaryButton></Card>})}</div></Page>;
}

export function KnowledgePage() {
  const {workspaceId}=useAuth();const query=useData<any>('/api/intelligence/knowledge',{documents:[]});const [open,setOpen]=useState(false);const [form,setForm]=useState({title:'',source_type:'faq',content:'',approved:false});const [error,setError]=useState('');
  const create=async(e:React.FormEvent)=>{e.preventDefault();if(!workspaceId)return;try{await apiFetch('/api/intelligence/knowledge',{method:'POST',body:JSON.stringify(form)},workspaceId);setOpen(false);setForm({title:'',source_type:'faq',content:'',approved:false});await query.refresh()}catch(err:any){setError(err.message)}};
  return <Page title="Knowledge" eyebrow="Business truth" action={<PrimaryButton onClick={()=>setOpen(!open)}><Plus className="mr-2 inline h-4 w-4"/>Add knowledge</PrimaryButton>}>{open&&<Card className="mb-5 p-5"><form onSubmit={create} className="space-y-3"><Field label="Title" value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))} required/><SelectField label="Type" value={form.source_type} onChange={e=>setForm(v=>({...v,source_type:e.target.value}))}><option value="faq">FAQ</option><option value="policy">Policy</option><option value="manual">Manual note</option><option value="pricing">Pricing</option><option value="website">Website</option></SelectField><TextareaField label="Content" value={form.content} onChange={e=>setForm(v=>({...v,content:e.target.value}))} required/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.approved} onChange={e=>setForm(v=>({...v,approved:e.target.checked}))}/>Approved for Operator retrieval</label>{error&&<p className="text-sm text-red-600">{error}</p>}<PrimaryButton>Save knowledge</PrimaryButton></form></Card>}{query.loading?<Spinner/>:query.data.documents.length?<div className="grid gap-3 md:grid-cols-2">{query.data.documents.map((d:any)=><Card key={d.id} className="p-4"><div className="flex items-start justify-between"><div><p className="font-semibold">{d.title}</p><p className="mt-1 text-xs text-slate-500">{d.source_type}</p></div><StatusPill tone={d.approved?'green':'amber'}>{d.approved?'approved':'draft'}</StatusPill></div></Card>)}</div>:<EmptyState title="No business knowledge yet" description="Approved FAQs, policies, pricing and service information become controlled retrieval sources for the Operator."/>}</Page>;
}

export function ApprovalsPage() { const {workspaceId}=useAuth(); const query=useData<any>('/api/intelligence/approvals',{approvals:[]}); const decide=async(id:string,decision:string)=>{if(!workspaceId)return;await apiFetch(`/api/intelligence/approvals/${id}/decision`,{method:'POST',body:JSON.stringify({decision,note:''})},workspaceId);await query.refresh()}; return <Page title="Approvals" eyebrow="Human control">{query.loading?<Spinner/>:query.data.approvals.length?<div className="space-y-3">{query.data.approvals.map((a:any)=><Card key={a.id} className="p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><p className="font-bold">{a.resource_type}</p><StatusPill tone={a.status==='pending'?'amber':a.status==='approved'?'green':'red'}>{a.status}</StatusPill></div><p className="mt-2 text-sm text-slate-600">{a.reason}</p></div>{a.status==='pending'&&<div className="flex gap-2"><SecondaryButton onClick={()=>decide(a.id,'rejected')}>Reject</SecondaryButton><PrimaryButton onClick={()=>decide(a.id,'approved')}>Approve</PrimaryButton></div>}</div></Card>)}</div>:<EmptyState title="No approvals waiting" description="High-risk AI actions, unusual pricing and configured approval gates appear here."/>}</Page> }

export function OperatorPage() { const query=useData<any>('/api/intelligence/ai-actions',{actions:[]}); return <Page title="Operator" eyebrow="AI action log">{query.loading?<Spinner/>:query.data.actions.length?<Card className="overflow-hidden"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">Tool</th><th className="px-4 py-3">Risk</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Time</th></tr></thead><tbody>{query.data.actions.map((a:any)=><tr key={a.id} className="border-t border-slate-100"><td className="px-4 py-3 font-mono text-xs">{a.tool_name}</td><td className="px-4 py-3"><StatusPill tone={a.risk_level==='high'?'red':a.risk_level==='medium'?'amber':'green'}>{a.risk_level}</StatusPill></td><td className="px-4 py-3">{a.status}</td><td className="px-4 py-3 text-slate-500">{new Date(a.created_at).toLocaleString('en-AU')}</td></tr>)}</tbody></table></Card>:<EmptyState title="No Operator actions yet" description="Every controlled AI tool call will be recorded here with risk, approval and outcome."/>}</Page> }

export function AutomationsPage() { const query=useData<any>('/api/intelligence/automations',{automations:[]}); return <Page title="Automations" eyebrow="Trigger → conditions → actions">{query.loading?<Spinner/>:query.data.automations.length?<div className="grid gap-4 md:grid-cols-2">{query.data.automations.map((a:any)=><Card key={a.id} className="p-5"><div className="flex items-center justify-between"><h3 className="font-bold">{a.name}</h3><StatusPill tone={a.status==='active'?'green':'slate'}>{a.status}</StatusPill></div><p className="mt-2 text-sm text-slate-500">{a.description}</p><p className="mt-4 text-xs font-semibold text-indigo-600">Trigger: {a.trigger_key}</p></Card>)}</div>:<EmptyState title="No automations yet" description="The versioned automation and run tables are live. The visual builder and background worker are deliberately not pretending to execute until durable jobs are configured."/>}</Page> }

export function ReviewsPage() { const query=useData<any>('/api/intelligence/reviews',{reviews:[]}); return <Page title="Reviews" eyebrow="Reputation engine">{query.loading?<Spinner/>:query.data.reviews.length?<div className="space-y-3">{query.data.reviews.map((r:any)=><Card key={r.id} className="p-4"><div className="flex justify-between"><div><p className="font-semibold">{r.customers?.display_name||'Customer'}</p><p className="text-xs text-slate-500">{r.channel} · {r.status}</p></div><span className="font-black">{r.rating?`${r.rating}/5`:'—'}</span></div>{r.feedback&&<p className="mt-3 text-sm text-slate-600">{r.feedback}</p>}</Card>)}</div>:<EmptyState title="No review requests yet" description="Post-job review requests and sensitive-feedback escalation will appear here once communication delivery is connected."/>}</Page> }

export function AnalyticsPage() { const query=useData<any>('/api/intelligence/attribution',{sources:[],events:[]}); const total=(query.data.sources||[]).reduce((s:number,r:any)=>s+r.revenueCents,0); return <Page title="Analytics" eyebrow="Revenue attribution"><Card className="mb-5 p-6"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Jobryn-attributed revenue</p><div className="mt-2 text-5xl font-black"><Money cents={total}/></div></Card>{query.loading?<Spinner/>:query.data.sources.length?<Card className="overflow-hidden"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">Source</th><th className="px-4 py-3">Conversions</th><th className="px-4 py-3 text-right">Revenue</th></tr></thead><tbody>{query.data.sources.map((s:any)=><tr key={s.source} className="border-t border-slate-100"><td className="px-4 py-3 font-semibold">{s.source}</td><td className="px-4 py-3 text-slate-500">{s.conversions}</td><td className="px-4 py-3 text-right font-bold"><Money cents={s.revenueCents}/></td></tr>)}</tbody></table></Card>:<EmptyState title="No attributed revenue yet" description="As payments are linked to source → lead → booking → job, this page becomes Jobryn's core ROI proof."/>}</Page> }

export function TeamPage() { const query=useData<any>('/api/team',{members:[]}); return <Page title="Team" eyebrow="Workspace access">{query.loading?<Spinner/>:<div className="grid gap-3 md:grid-cols-2">{query.data.members.map((m:any)=><Card key={m.user_id} className="p-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-100 font-bold">{(m.profile?.display_name||'?')[0]}</div><div className="min-w-0 flex-1"><p className="font-semibold">{m.profile?.display_name||m.user_id.slice(0,8)}</p><p className="text-xs text-slate-500">{m.role}</p></div><StatusPill tone={m.status==='active'?'green':'slate'}>{m.status}</StatusPill></div></Card>)}</div>}</Page> }

export function SecuritySettingsPage() {
  const {refreshMfa}=useAuth(); const [factors,setFactors]=useState<any[]>([]); const [enrollment,setEnrollment]=useState<any>(null); const [code,setCode]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);const {data,error}=await supabase.auth.mfa.listFactors();if(error)setError(error.message);else setFactors(data.totp);setLoading(false)};useEffect(()=>{void load()},[]);
  const enroll=async()=>{setError('');const {data,error}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'Jobryn Authenticator'});if(error)return setError(error.message);setEnrollment(data)};
  const verify=async()=>{if(!enrollment)return;const {error}=await supabase.auth.mfa.challengeAndVerify({factorId:enrollment.id,code});if(error)return setError(error.message);setEnrollment(null);setCode('');await refreshMfa();await load()};
  const remove=async(id:string)=>{const {error}=await supabase.auth.mfa.unenroll({factorId:id});if(error)return setError(error.message);await refreshMfa();await load()};
  return <Page title="Security" eyebrow="Account protection"><div className="grid gap-5 xl:grid-cols-2"><Card className="p-6"><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><LockKeyhole className="h-5 w-5"/></div><div><h3 className="font-bold">Authenticator MFA</h3><p className="mt-1 text-sm leading-6 text-slate-500">Add TOTP to protect account takeover and allow AAL2 enforcement on sensitive owner/admin routes.</p></div></div>{loading?<Spinner/>:<div className="mt-5 space-y-3">{factors.map(f=><div key={f.id} className="flex items-center justify-between rounded-xl border border-slate-200 p-3"><div><p className="text-sm font-semibold">{f.friendly_name||'Authenticator app'}</p><p className="text-xs text-slate-500">{f.status}</p></div><SecondaryButton onClick={()=>remove(f.id)}>Remove</SecondaryButton></div>)}{!factors.some(f=>f.status==='verified')&&!enrollment&&<PrimaryButton onClick={enroll}>Set up authenticator</PrimaryButton>}</div>}{enrollment&&<div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="mb-3 text-sm font-semibold">Scan this QR code, then verify a code.</p><img src={enrollment.totp.qr_code} alt="Authenticator QR code" className="h-44 w-44 rounded-lg bg-white p-2"/><p className="mt-2 break-all text-[10px] text-slate-500">Secret: {enrollment.totp.secret}</p><div className="mt-4 flex gap-2"><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} maxLength={6} placeholder="123456" className="w-32 rounded-xl border border-slate-200 px-3 py-2 text-sm"/><PrimaryButton onClick={verify}>Verify</PrimaryButton></div></div>}{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}</Card><Card className="p-6"><h3 className="font-bold">Security boundaries in this build</h3><div className="mt-4 space-y-3">{['PKCE social login and email authentication','Workspace membership verified on the API','PostgreSQL RLS on tenant-owned tables','Server-only Stripe and Supabase service keys','Signed Stripe webhook verification','Strict body validation and API rate limits','Append-only operational audit trail'].map(item=><div key={item} className="flex gap-2 text-sm text-slate-600"><CheckCircle2 className="mt-0.5 h-4 w-4 flex-none text-emerald-600"/>{item}</div>)}</div></Card></div></Page>;
}

export function CampaignsPage() { return <Page title="Campaigns" eyebrow="Acquire + reactivate"><div className="grid gap-5 lg:grid-cols-2"><Card className="p-6"><h3 className="font-bold">Campaign OS foundation retained</h3><p className="mt-2 text-sm leading-6 text-slate-500">The existing Campaign OS code has been preserved in this repository instead of discarded. Its legacy demo state should only be used for development until each asset/content path is moved to normalized persistence.</p><AppLink href="/app/campaigns/legacy" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-indigo-600">Open retained Campaign OS <ArrowRight className="h-4 w-4"/></AppLink></Card><Card className="p-6"><h3 className="font-bold">Revenue-connected campaign model</h3><p className="mt-2 text-sm leading-6 text-slate-500">Campaigns already share the workspace database with CRM and revenue attribution, so future sends can be measured against real bookings and payments.</p></Card></div></Page> }

export function ModulePage({title,eyebrow,description,status='Backend schema ready'}:{title:string;eyebrow:string;description:string;status?:string}) { return <Page title={title} eyebrow={eyebrow}><Card className="p-7"><div className="flex items-start justify-between gap-4"><div><h3 className="text-xl font-bold">{title}</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{description}</p></div><StatusPill tone="amber">{status}</StatusPill></div><div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-800">This screen does not fake external actions. It stays visibly limited until the required provider, worker or controlled Operator tool is connected and tested.</div></Card></Page> }

export function SettingsPage() { return <Page title="Settings" eyebrow="Workspace configuration"><div className="grid gap-4 md:grid-cols-2">{[['Business profile','Update business identity, trading details and service context.','/onboarding'],['Services & pricing','Configure approved services and prices.','/onboarding'],['Security','MFA and security posture.','/app/settings/security'],['Billing','Plan, subscription and Stripe portal.','/app/billing']].map(([title,desc,href])=><AppLink key={title} href={href} className="block"><Card className="h-full p-5 transition hover:border-indigo-300"><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{desc}</p></Card></AppLink>)}</div></Page> }

function ErrorBox({message,onRetry}:{message:string;onRetry?:()=>void}) { return <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700"><div className="flex items-center gap-2 font-semibold"><AlertTriangle className="h-4 w-4"/>Could not load this page</div><p className="mt-2">{message}</p>{onRetry&&<button onClick={onRetry} className="mt-3 text-xs font-bold underline">Try again</button>}</div> }
function Page({title,eyebrow,action,children}:{title:string;eyebrow:string;action?:React.ReactNode;children:React.ReactNode}) { return <div><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-600">{eyebrow}</p><h1 className="mt-1 text-3xl font-black tracking-tight">{title}</h1></div>{action}</div>{children}</div> }
