import React,{useEffect,useState} from 'react';
import {Brain,ChevronRight,History,Search,ShieldCheck,SlidersHorizontal} from 'lucide-react';
import {useAuth} from '../app/auth';
import {apiFetch} from '../lib/api';
import {Card,EmptyState,PrimaryButton,SecondaryButton,Spinner,StatusPill} from '../components/saas/ui';

const statuses=['active','candidate','challenged','stale','archived'] as const;
const settingLabels:Record<string,string>={communication_style:'Communication style',duration_estimates:'Job duration estimates',quote_adjustments:'Repeated quote adjustments',pricing_optimisation:'Pricing optimisation',technician_comparisons:'Technician comparisons',payment_predictions:'Payment predictions',travel_calibration:'Travel calibration',supplier_forecasting:'Supplier forecasting',sensitive_property_memory:'Sensitive property memory'};

export function BusinessBrainPage(){
  const{workspaceId}=useAuth();const[status,setStatus]=useState<(typeof statuses)[number]>('active');const[memories,setMemories]=useState<any[]>([]);const[selected,setSelected]=useState<any>(null);const[settings,setSettings]=useState<any>(null);const[metrics,setMetrics]=useState<any>({});const[search,setSearch]=useState('');const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busy,setBusy]=useState('');
  const load=async()=>{if(!workspaceId)return;setLoading(true);setError('');try{const[m,s,x]=await Promise.all([apiFetch<any>(`/api/business-brain/memories?status=${status}&search=${encodeURIComponent(search)}`,{},workspaceId),apiFetch<any>('/api/business-brain/settings',{},workspaceId),apiFetch<any>('/api/business-brain/metrics',{},workspaceId)]);setMemories(m.memories||[]);setSettings(s.settings);setMetrics(x)}catch(err:any){setError(err.message)}finally{setLoading(false)}};
  useEffect(()=>{void load()},[workspaceId,status]);
  const open=async(id:string)=>{if(!workspaceId)return;setBusy(id);try{setSelected(await apiFetch(`/api/business-brain/memories/${id}`,{},workspaceId))}finally{setBusy('')}};
  const decide=async(decision:string)=>{if(!workspaceId||!selected?.memory)return;const reason=decision==='confirm'?'Reviewed and confirmed for future suggestions.':decision==='challenge'?'Evidence needs review before this can influence suggestions.':decision==='archive'?'No longer relevant to current business operations.':'Permanently removed at workspace request.';setBusy(decision);try{await apiFetch(`/api/business-brain/memories/${selected.memory.id}/decision`,{method:'POST',body:JSON.stringify({decision,reason})},workspaceId);setSelected(null);await load()}catch(err:any){setError(err.message)}finally{setBusy('')}};
  const saveSettings=async(next:any)=>{if(!workspaceId)return;setSettings(next);try{const allowed=Object.fromEntries(Object.keys(settingLabels).map(key=>[key,Boolean(next[key])]));const result=await apiFetch<any>('/api/business-brain/settings',{method:'PUT',body:JSON.stringify(allowed)},workspaceId);setSettings(result.settings)}catch(err:any){setError(err.message);await load()}};
  return <section><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-600">Evidence-driven learning</p><h1 className="mt-1 text-3xl font-black tracking-tight">AI Memory</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">See exactly what Jobryn has learned, why it learned it, and where it influenced a suggestion. A correction never becomes a general rule by itself.</p></div><div className="flex items-center gap-2 rounded-xl bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700"><ShieldCheck className="h-4 w-4"/>Human-controlled learning</div></div>
    <div className="mb-5 grid gap-3 sm:grid-cols-4">{[['Active',metrics.memories?.active||0],['Needs review',metrics.memories?.candidate||0],['Challenged',metrics.memories?.challenged||0],['Accepted suggestions',metrics.usage?.accepted||0]].map(([label,value])=><Card key={String(label)} className="p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></Card>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1fr_340px]"><div><div className="mb-4 flex flex-wrap items-center gap-2">{statuses.map(item=><button key={item} onClick={()=>{setStatus(item);setSelected(null)}} className={`rounded-full px-3 py-2 text-xs font-bold capitalize ${status===item?'bg-slate-950 text-white':'border border-slate-200 bg-white text-slate-600'}`}>{item}</button>)}<form className="ml-auto flex min-w-64 gap-2" onSubmit={e=>{e.preventDefault();void load()}}><div className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search memories" className="w-full rounded-xl border border-slate-200 py-2 pl-9 pr-3 text-sm"/></div></form></div>
      {loading?<Spinner label="Loading memory…"/>:error?<Card className="border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</Card>:memories.length?<div className="space-y-3">{memories.map(memory=><button key={memory.id} onClick={()=>open(memory.id)} className="block w-full text-left"><Card className="p-5 transition hover:border-indigo-300"><div className="flex items-start gap-4"><div className="flex h-10 w-10 flex-none items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><Brain className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{memory.summary}</p><StatusPill tone={memory.status==='active'?'green':memory.status==='challenged'?'red':memory.status==='candidate'?'amber':'slate'}>{memory.status}</StatusPill><StatusPill>{memory.sensitivity}</StatusPill></div><p className="mt-2 text-xs text-slate-500">{memory.scope_type} · {memory.category} · {memory.sample_count} supporting observation{memory.sample_count===1?'':'s'} · {Math.round(Number(memory.confidence)*100)}% confidence</p></div><ChevronRight className="mt-2 h-4 w-4 text-slate-400"/></div></Card></button>)}</div>:<EmptyState title={`No ${status} memories`} description="Jobryn only shows learned patterns after evidence is captured and the deterministic validation rules are satisfied."/>}</div>
      <div className="space-y-5">{selected?<Card className="p-5"><div className="flex items-center gap-2"><History className="h-4 w-4 text-indigo-600"/><h2 className="font-bold">Evidence and influence</h2></div><p className="mt-3 text-sm font-semibold">{selected.memory.summary}</p><pre className="mt-3 max-h-48 overflow-auto rounded-xl bg-slate-950 p-3 text-[11px] text-slate-200">{JSON.stringify(selected.memory.structured_value,null,2)}</pre><div className="mt-4"><p className="text-xs font-bold uppercase text-slate-400">Evidence</p>{selected.evidence.length?selected.evidence.map((e:any)=><div key={e.id} className="mt-2 rounded-xl border border-slate-200 p-3 text-xs"><b>{e.source_type}</b> · {new Date(e.event_at).toLocaleDateString('en-AU')}<p className="mt-1 text-slate-500">Weight {e.weight}{e.explicitly_confirmed?' · explicitly confirmed':''}</p></div>):<p className="mt-2 text-xs text-slate-500">No evidence rows available.</p>}</div><div className="mt-4 flex flex-wrap gap-2">{selected.memory.status!=='active'&&<PrimaryButton disabled={!!busy} onClick={()=>decide('confirm')}>Confirm</PrimaryButton>}<SecondaryButton disabled={!!busy} onClick={()=>decide('challenge')}>Challenge</SecondaryButton><SecondaryButton disabled={!!busy} onClick={()=>decide('archive')}>Archive</SecondaryButton><button disabled={!!busy} onClick={()=>decide('delete')} className="text-xs font-bold text-red-600 disabled:opacity-50">Delete permanently</button></div></Card>:<Card className="p-5"><h2 className="font-bold">How this works</h2><p className="mt-2 text-sm leading-6 text-slate-500">Select a memory to inspect every supporting record, promotion decision, and suggestion it influenced.</p></Card>}
      {settings&&<Card className="p-5"><div className="flex items-center gap-2"><SlidersHorizontal className="h-4 w-4 text-indigo-600"/><h2 className="font-bold">Learning controls</h2></div><div className="mt-4 space-y-2">{Object.entries(settingLabels).map(([key,label])=>{const locked=!['communication_style','duration_estimates','quote_adjustments'].includes(key);return <label key={key} className={`flex items-center justify-between rounded-xl border border-slate-200 p-3 text-sm ${locked?'bg-slate-50 text-slate-400':''}`}><span>{label}{locked&&<small className="ml-1">(later release)</small>}</span><input type="checkbox" disabled={locked} checked={Boolean(settings[key])} onChange={e=>saveSettings({...settings,[key]:e.target.checked})}/></label>})}</div></Card>}</div></div>
  </section>;
}
