import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { ArrowLeft, CalendarClock, CheckCircle2, CircleDollarSign, Clock3, FileText, Mail, MapPin, Phone, UserRound } from 'lucide-react';
import { useAuth } from '../app/auth';
import { AppLink } from '../app/router';
import { apiFetch } from '../lib/api';
import { Card, EmptyState, Field, Money, PrimaryButton, SecondaryButton, Spinner, StatusPill } from '../components/saas/ui';

function tone(status: string): 'slate'|'green'|'amber'|'red'|'indigo' {
  if (['paid','completed','succeeded','accepted'].includes(status)) return 'green';
  if (['overdue','failed','cancelled','lost'].includes(status)) return 'red';
  if (['new','scheduled','sent','viewed','part_paid'].includes(status)) return 'amber';
  return 'slate';
}

function formatDate(value?: string | null) {
  return value ? new Date(value).toLocaleString('en-AU', { day:'numeric', month:'short', year:'numeric', hour:'numeric', minute:'2-digit' }) : 'Not set';
}

function toLocalInput(value?: string | null) {
  if (!value) return '';
  const date = new Date(value);
  const offset = date.getTimezoneOffset() * 60_000;
  return new Date(date.getTime() - offset).toISOString().slice(0, 16);
}

export function JobDetailPage({ id }: { id: string }) {
  const { workspaceId } = useAuth();
  const [data,setData] = useState<any>(null); const [loading,setLoading] = useState(true); const [error,setError] = useState(''); const [busy,setBusy] = useState('');
  const [scheduleOpen,setScheduleOpen] = useState(false); const [start,setStart] = useState(''); const [end,setEnd] = useState('');
  const load = async()=>{if(!workspaceId)return;setLoading(true);setError('');try{const result=await apiFetch<any>(`/api/operations/jobs/${id}`,{},workspaceId);setData(result);setStart(toLocalInput(result.job.scheduled_start));setEnd(toLocalInput(result.job.scheduled_end))}catch(err:any){setError(err.message)}finally{setLoading(false)}};
  useEffect(()=>{void load()},[workspaceId,id]);
  const next = useMemo(()=>({new:'in_progress',scheduled:'on_the_way',on_the_way:'in_progress',in_progress:'completed',completed:'invoiced',invoiced:'paid'} as Record<string,string>)[data?.job?.status],[data?.job?.status]);
  const actionLabel:Record<string,string>={in_progress:'Start work',on_the_way:'Mark on the way',completed:'Complete job',invoiced:'Mark invoiced',paid:'Mark paid'};
  const changeStatus=async(status:string)=>{if(!workspaceId)return;setBusy(status);setError('');try{await apiFetch(`/api/operations/jobs/${id}/status`,{method:'PATCH',body:JSON.stringify({status})},workspaceId);await load()}catch(err:any){setError(err.message)}finally{setBusy('')}};
  const saveSchedule=async(e:React.FormEvent)=>{e.preventDefault();if(!workspaceId)return;setBusy('schedule');setError('');try{await apiFetch(`/api/operations/jobs/${id}/schedule`,{method:'PATCH',body:JSON.stringify({scheduled_start:new Date(start).toISOString(),scheduled_end:new Date(end).toISOString()})},workspaceId);setScheduleOpen(false);await load()}catch(err:any){setError(err.message)}finally{setBusy('')}};
  if(loading)return <Spinner label="Loading job workspace…"/>;
  if(error&&!data)return <EmptyState title="Job could not be opened" description={error} action={<SecondaryButton onClick={load}>Try again</SecondaryButton>}/>;
  const {job,appointments,quotes,invoices,payments}=data;
  const canAdvance = next && !(next==='invoiced'&&!invoices.length) && !(next==='paid'&&invoices.some((invoice:any)=>Number(invoice.balance_due_cents)>0));
  return <div className="space-y-5">
    <div><AppLink href="/app/jobs" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-950"><ArrowLeft className="h-4 w-4"/>Back to jobs</AppLink><div className="mt-4 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Job #{job.job_number}</p><StatusPill tone={tone(job.status)}>{job.status.replaceAll('_',' ')}</StatusPill></div><h1 className="mt-2 text-3xl font-black tracking-tight">{job.title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{job.description||'No work description has been added.'}</p></div><div className="flex flex-wrap gap-2"><SecondaryButton onClick={()=>setScheduleOpen(v=>!v)}><CalendarClock className="mr-2 inline h-4 w-4"/>{job.scheduled_start?'Reschedule':'Schedule job'}</SecondaryButton>{canAdvance&&<PrimaryButton disabled={Boolean(busy)} onClick={()=>changeStatus(next)}>{busy===next?'Updating…':actionLabel[next]}</PrimaryButton>}</div></div></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {scheduleOpen&&<Card className="p-5"><form onSubmit={saveSchedule} className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><h2 className="font-bold">Job schedule</h2><p className="mt-1 text-sm text-slate-500">Both times are required. Jobryn checks the time range before saving.</p></div><Field label="Start" type="datetime-local" required value={start} onChange={e=>{setStart(e.target.value);if(e.target.value&&!end){const d=new Date(e.target.value);d.setHours(d.getHours()+1);setEnd(toLocalInput(d.toISOString()))}}}/><Field label="Finish" type="datetime-local" required value={end} onChange={e=>setEnd(e.target.value)}/><div className="flex gap-2 sm:col-span-2"><PrimaryButton disabled={busy==='schedule'}>{busy==='schedule'?'Saving…':'Save schedule'}</PrimaryButton><SecondaryButton type="button" onClick={()=>setScheduleOpen(false)}>Cancel</SecondaryButton></div></form></Card>}
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="space-y-5"><Card className="p-5"><h2 className="font-bold">Job overview</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Info icon={UserRound} label="Customer" value={job.customers?.display_name||'No customer'} href={job.customer_id?`/app/customers/${job.customer_id}`:undefined}/><Info icon={MapPin} label="Address" value={job.address_text||'Not added'}/><Info icon={CalendarClock} label="Start" value={formatDate(job.scheduled_start)}/><Info icon={Clock3} label="Finish" value={formatDate(job.scheduled_end)}/></div></Card><Card className="p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Quotes and invoices</h2><AppLink href={`/app/quotes?job=${job.id}`} className="text-xs font-semibold text-indigo-600">Create quote</AppLink></div><div className="mt-4 space-y-2">{quotes.map((row:any)=><MoneyRow key={`q${row.id}`} icon={FileText} label={`Quote #${row.quote_number}`} status={row.status} cents={row.total_cents}/>) }{invoices.map((row:any)=><MoneyRow key={`i${row.id}`} icon={CircleDollarSign} label={`Invoice #${row.invoice_number}`} status={row.status} cents={row.balance_due_cents} suffix=" outstanding"/>)}{!quotes.length&&!invoices.length&&<EmptyState title="No financial documents" description="Create a quote or invoice from this job so revenue stays connected to the work."/>}</div></Card></div>
      <div className="space-y-5"><Card className="p-5"><h2 className="font-bold">Recommended next step</h2><p className="mt-2 text-sm leading-6 text-slate-500">{next==='invoiced'&&!invoices.length?'Create an invoice before marking this job invoiced.':next==='paid'&&!canAdvance?'The job will become paid automatically only after its invoice balance is settled.':next?`${actionLabel[next]} when the business has genuinely reached that stage.`:'No further lifecycle action is required.'}</p>{next==='invoiced'&&!invoices.length&&<AppLink href={`/app/invoices?job=${job.id}`} className="mt-4 inline-flex rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Create invoice</AppLink>}</Card><Card className="p-5"><h2 className="font-bold">Activity</h2><div className="mt-4 space-y-3"><Activity label="Job created" date={job.created_at}/>{appointments.map((row:any)=><Activity key={row.id} label={`Appointment ${row.status}`} date={row.starts_at}/>)}{quotes.map((row:any)=><Activity key={row.id} label={`Quote #${row.quote_number} ${row.status}`} date={row.created_at}/>)}{invoices.map((row:any)=><Activity key={row.id} label={`Invoice #${row.invoice_number} ${row.status}`} date={row.created_at}/>)}{payments.map((row:any)=><Activity key={row.id} label={`Payment ${row.status}`} date={row.paid_at||row.created_at}/>)}</div></Card></div></div>
  </div>;
}

export function CustomerDetailPage({ id }: { id: string }) {
  const {workspaceId}=useAuth(); const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  useEffect(()=>{if(!workspaceId)return;setLoading(true);apiFetch<any>(`/api/crm/customers/${id}`,{},workspaceId).then(setData).catch((err:any)=>setError(err.message)).finally(()=>setLoading(false))},[workspaceId,id]);
  if(loading)return <Spinner label="Loading customer workspace…"/>;
  if(error||!data)return <EmptyState title="Customer could not be opened" description={error||'Customer not found.'}/>;
  const {customer,addresses,leads,jobs,quotes,invoices,payments,calls}=data; const outstanding=invoices.reduce((sum:number,row:any)=>sum+Number(row.balance_due_cents||0),0);
  return <div className="space-y-5"><div><AppLink href="/app/customers" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="h-4 w-4"/>Back to customers</AppLink><div className="mt-4 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Customer workspace</p><h1 className="mt-2 text-3xl font-black tracking-tight">{customer.display_name}</h1><div className="mt-3 flex flex-wrap gap-4 text-sm text-slate-500">{customer.phone&&<a href={`tel:${customer.phone}`} className="inline-flex items-center gap-1.5"><Phone className="h-4 w-4"/>{customer.phone}</a>}{customer.email&&<a href={`mailto:${customer.email}`} className="inline-flex items-center gap-1.5"><Mail className="h-4 w-4"/>{customer.email}</a>}</div></div><AppLink href={`/app/jobs?customer=${customer.id}`} className="inline-flex rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Create job</AppLink></div></div>
    <div className="grid gap-4 md:grid-cols-3"><Metric label="Lifetime value" value={<Money cents={customer.lifetime_value_cents||0}/>}/><Metric label="Outstanding" value={<Money cents={outstanding}/>}/><Metric label="Jobs" value={String(jobs.length)}/></div>
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="space-y-5"><Card className="overflow-hidden"><SectionHead title="Jobs"/><RecordTable rows={jobs.map((row:any)=>({id:row.id,label:row.title,status:row.status,value:formatDate(row.scheduled_start),href:`/app/jobs/${row.id}`}))} empty="No jobs for this customer."/></Card><Card className="overflow-hidden"><SectionHead title="Quotes and invoices"/><RecordTable rows={[...quotes.map((row:any)=>({id:`q${row.id}`,label:`Quote #${row.quote_number}`,status:row.status,value:new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(row.total_cents/100)})),...invoices.map((row:any)=>({id:`i${row.id}`,label:`Invoice #${row.invoice_number}`,status:row.status,value:new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(row.balance_due_cents/100)}))]} empty="No quotes or invoices for this customer."/></Card></div><div className="space-y-5"><Card className="p-5"><h2 className="font-bold">Customer details</h2><div className="mt-4 space-y-3 text-sm"><Detail label="Source" value={customer.source||'Not recorded'}/><Detail label="Notes" value={customer.notes||'No notes'}/><Detail label="Tags" value={(customer.tags||[]).join(', ')||'No tags'}/>{addresses.map((address:any)=><Detail key={address.id} label={address.label||'Address'} value={[address.street,address.suburb,address.state,address.postcode].filter(Boolean).join(', ')}/>)}</div></Card><Card className="p-5"><h2 className="font-bold">Recent contact</h2><div className="mt-4 space-y-3">{calls.slice(0,8).map((call:any)=><Activity key={call.id} label={`${call.direction} call · ${call.status}${call.summary?` · ${call.summary}`:''}`} date={call.started_at}/>)}{!calls.length&&<p className="text-sm text-slate-500">No calls recorded.</p>}</div></Card><Card className="p-5"><h2 className="font-bold">Sales history</h2><div className="mt-4 space-y-3">{leads.slice(0,8).map((lead:any)=><div key={lead.id} className="flex items-center justify-between gap-3 text-sm"><span className="font-medium">{lead.title}</span><StatusPill tone={tone(lead.stage)}>{lead.stage}</StatusPill></div>)}{!leads.length&&<p className="text-sm text-slate-500">No leads recorded.</p>}</div></Card></div></div>
  </div>;
}

function Info({icon:Icon,label,value,href}:{icon:any;label:string;value:string;href?:string}) { const content=<><Icon className="h-4 w-4 text-slate-400"/><div><p className="text-xs font-semibold text-slate-400">{label}</p><p className="mt-0.5 text-sm font-semibold text-slate-800">{value}</p></div></>; return href?<AppLink href={href} className="flex gap-3 rounded-xl bg-slate-50 p-3 hover:bg-slate-100">{content}</AppLink>:<div className="flex gap-3 rounded-xl bg-slate-50 p-3">{content}</div> }
function MoneyRow({icon:Icon,label,status,cents,suffix='' }:{icon:any;label:string;status:string;cents:number;suffix?:string}) { return <div className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><Icon className="h-4 w-4 text-slate-400"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{label}</p><p className="text-xs text-slate-500"><Money cents={cents}/>{suffix}</p></div><StatusPill tone={tone(status)}>{status}</StatusPill></div> }
function Activity({label,date}:{label:string;date?:string|null}) { return <div className="flex gap-3"><span className="mt-1.5 h-2 w-2 flex-none rounded-full bg-indigo-500"/><div><p className="text-sm font-medium text-slate-800">{label}</p><p className="text-xs text-slate-400">{formatDate(date)}</p></div></div> }
function Metric({label,value}:{label:string;value:ReactNode}) { return <Card className="p-5"><p className="text-xs font-semibold text-slate-500">{label}</p><div className="mt-2 text-3xl font-black">{value}</div></Card> }
function SectionHead({title}:{title:string}) { return <div className="border-b border-slate-100 bg-slate-50 px-5 py-3"><h2 className="font-bold">{title}</h2></div> }
function RecordTable({rows,empty}:{rows:Array<{id:string;label:string;status:string;value:string;href?:string}>;empty:string}) { if(!rows.length)return <div className="p-5 text-sm text-slate-500">{empty}</div>;return <div className="divide-y divide-slate-100">{rows.map(row=><div key={row.id} className="flex items-center gap-3 px-5 py-3"><div className="min-w-0 flex-1">{row.href?<AppLink href={row.href} className="font-semibold hover:text-indigo-700">{row.label}</AppLink>:<p className="font-semibold">{row.label}</p>}<p className="text-xs text-slate-500">{row.value}</p></div><StatusPill tone={tone(row.status)}>{row.status.replaceAll('_',' ')}</StatusPill></div>)}</div> }
function Detail({label,value}:{label:string;value:string}) { return <div><p className="text-xs font-semibold text-slate-400">{label}</p><p className="mt-0.5 leading-6 text-slate-700">{value}</p></div> }
